<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $now   = now();
        $depts = DB::table('departments')->pluck('id', 'code');

        // =========================================================================
        // COURSES
        // Each entry: code, name, name_ar, credit_hours, lecture_hours, lab_hours,
        //             level, is_elective, owner_dept_code
        // =========================================================================
        $courses = [

            // ── SHARED FOUNDATIONS (owned by CS, shared across CSIT depts) ───────
            [
                'code'          => 'MATH101',
                'name'          => 'Calculus I',
                'name_ar'       => 'حساب التفاضل والتكامل 1',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'CS',
                'shared_with'   => ['IS', 'CYB', 'AI'],
            ],
            [
                'code'          => 'MATH102',
                'name'          => 'Calculus II',
                'name_ar'       => 'حساب التفاضل والتكامل 2',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'CS',
                'shared_with'   => ['IS', 'CYB', 'AI'],
            ],
            [
                'code'          => 'MATH201',
                'name'          => 'Linear Algebra',
                'name_ar'       => 'الجبر الخطي',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'CS',
                'shared_with'   => ['AI', 'CYB'],
            ],
            [
                'code'          => 'MATH202',
                'name'          => 'Discrete Mathematics',
                'name_ar'       => 'الرياضيات المتقطعة',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'CS',
                'shared_with'   => ['IS', 'CYB'],
            ],
            [
                'code'          => 'CS101',
                'name'          => 'Introduction to Programming',
                'name_ar'       => 'مقدمة في البرمجة',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'CS',
                'shared_with'   => ['IS', 'CYB', 'AI'],
            ],
            [
                'code'          => 'CS102',
                'name'          => 'Data Structures',
                'name_ar'       => 'هياكل البيانات',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'CS',
                'shared_with'   => ['IS', 'AI'],
            ],
            [
                'code'          => 'CS103',
                'name'          => 'Object-Oriented Programming',
                'name_ar'       => 'البرمجة كائنية التوجه',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'CS',
                'shared_with'   => ['IS'],
            ],

            // ── COMPUTER SCIENCE (CS) ────────────────────────────────────────────
            [
                'code'          => 'CS201',
                'name'          => 'Algorithms & Complexity',
                'name_ar'       => 'الخوارزميات والتعقيد',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'CS',
                'shared_with'   => ['AI'],
            ],
            [
                'code'          => 'CS301',
                'name'          => 'Operating Systems',
                'name_ar'       => 'أنظمة التشغيل',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'CS',
                'shared_with'   => ['CYB'],
            ],
            [
                'code'          => 'CS302',
                'name'          => 'Computer Architecture',
                'name_ar'       => 'معمارية الحاسوب',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'CS',
                'shared_with'   => [],
            ],
            [
                'code'          => 'CS401',
                'name'          => 'Compiler Design',
                'name_ar'       => 'تصميم المترجمات',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'CS',
                'shared_with'   => [],
            ],
            [
                'code'          => 'CS402',
                'name'          => 'Distributed Systems',
                'name_ar'       => 'الأنظمة الموزعة',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 4,
                'is_elective'   => true,
                'owner'         => 'CS',
                'shared_with'   => ['IS'],
            ],

            // ── INFORMATION SYSTEMS (IS) ─────────────────────────────────────────
            [
                'code'          => 'IS201',
                'name'          => 'Database Design & Management',
                'name_ar'       => 'تصميم وإدارة قواعد البيانات',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'IS',
                'shared_with'   => ['CS', 'CYB'],
            ],
            [
                'code'          => 'IS301',
                'name'          => 'Systems Analysis & Design',
                'name_ar'       => 'تحليل وتصميم الأنظمة',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'IS',
                'shared_with'   => [],
            ],
            [
                'code'          => 'IS302',
                'name'          => 'Enterprise Resource Planning',
                'name_ar'       => 'تخطيط موارد المؤسسة',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'IS',
                'shared_with'   => [],
            ],
            [
                'code'          => 'IS401',
                'name'          => 'Business Intelligence & Analytics',
                'name_ar'       => 'ذكاء الأعمال والتحليلات',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'IS',
                'shared_with'   => ['AI'],
            ],

            // ── CYBERSECURITY (CYB) ──────────────────────────────────────────────
            [
                'code'          => 'CYB201',
                'name'          => 'Network Fundamentals',
                'name_ar'       => 'أساسيات الشبكات',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'CYB',
                'shared_with'   => ['IS', 'CS'],
            ],
            [
                'code'          => 'CYB301',
                'name'          => 'Ethical Hacking & Penetration Testing',
                'name_ar'       => 'الاختراق الأخلاقي واختبار الاختراق',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'CYB',
                'shared_with'   => [],
            ],
            [
                'code'          => 'CYB302',
                'name'          => 'Cryptography & Information Security',
                'name_ar'       => 'التشفير وأمن المعلومات',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'CYB',
                'shared_with'   => ['CS'],
            ],
            [
                'code'          => 'CYB401',
                'name'          => 'Digital Forensics',
                'name_ar'       => 'الجنائيات الرقمية',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'CYB',
                'shared_with'   => [],
            ],
            [
                'code'          => 'CYB402',
                'name'          => 'Cloud Security',
                'name_ar'       => 'أمن الحوسبة السحابية',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 4,
                'is_elective'   => true,
                'owner'         => 'CYB',
                'shared_with'   => [],
            ],

            // ── ARTIFICIAL INTELLIGENCE (AI) ─────────────────────────────────────
            [
                'code'          => 'AI201',
                'name'          => 'Probability & Statistics for AI',
                'name_ar'       => 'الاحتمالات والإحصاء للذكاء الاصطناعي',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'AI',
                'shared_with'   => ['CS'],
            ],
            [
                'code'          => 'AI301',
                'name'          => 'Machine Learning',
                'name_ar'       => 'التعلم الآلي',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'AI',
                'shared_with'   => ['CS', 'IS'],
            ],
            [
                'code'          => 'AI302',
                'name'          => 'Deep Learning & Neural Networks',
                'name_ar'       => 'التعلم العميق والشبكات العصبية',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'AI',
                'shared_with'   => [],
            ],
            [
                'code'          => 'AI401',
                'name'          => 'Natural Language Processing',
                'name_ar'       => 'معالجة اللغات الطبيعية',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'AI',
                'shared_with'   => [],
            ],
            [
                'code'          => 'AI402',
                'name'          => 'Computer Vision',
                'name_ar'       => 'رؤية الحاسوب',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 4,
                'is_elective'   => true,
                'owner'         => 'AI',
                'shared_with'   => [],
            ],

            // ── ENGINEERING PREPARATORY (ENG-PREP) ───────────────────────────────
            [
                'code'          => 'ENG001',
                'name'          => 'Engineering Mathematics I',
                'name_ar'       => 'رياضيات هندسية 1',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'ENG-PREP',
                'shared_with'   => ['CIVIL', 'ELEC', 'MECH', 'ARCH'],
            ],
            [
                'code'          => 'ENG002',
                'name'          => 'Engineering Mathematics II',
                'name_ar'       => 'رياضيات هندسية 2',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'ENG-PREP',
                'shared_with'   => ['CIVIL', 'ELEC', 'MECH', 'ARCH'],
            ],
            [
                'code'          => 'ENG003',
                'name'          => 'Engineering Drawing & CAD',
                'name_ar'       => 'الرسم الهندسي والتصميم بالحاسوب',
                'credit_hours'  => 2,
                'lecture_hours' => 1,
                'lab_hours'     => 2,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'ENG-PREP',
                'shared_with'   => ['CIVIL', 'MECH', 'ARCH'],
            ],
            [
                'code'          => 'ENG004',
                'name'          => 'Engineering Physics',
                'name_ar'       => 'الفيزياء الهندسية',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'ENG-PREP',
                'shared_with'   => ['CIVIL', 'ELEC', 'MECH'],
            ],

            // ── CIVIL ENGINEERING (CIVIL) ─────────────────────────────────────────
            [
                'code'          => 'CIVIL201',
                'name'          => 'Mechanics of Materials',
                'name_ar'       => 'ميكانيكا المواد',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'CIVIL',
                'shared_with'   => ['MECH'],
            ],
            [
                'code'          => 'CIVIL202',
                'name'          => 'Fluid Mechanics',
                'name_ar'       => 'ميكانيكا الموائع',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'CIVIL',
                'shared_with'   => ['MECH'],
            ],
            [
                'code'          => 'CIVIL301',
                'name'          => 'Structural Analysis',
                'name_ar'       => 'تحليل الإنشاءات',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'CIVIL',
                'shared_with'   => [],
            ],
            [
                'code'          => 'CIVIL302',
                'name'          => 'Geotechnical Engineering',
                'name_ar'       => 'الهندسة الجيوتقنية',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'CIVIL',
                'shared_with'   => [],
            ],
            [
                'code'          => 'CIVIL401',
                'name'          => 'Reinforced Concrete Design',
                'name_ar'       => 'تصميم الخرسانة المسلحة',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'CIVIL',
                'shared_with'   => [],
            ],

            // ── ELECTRICAL ENGINEERING (ELEC) ─────────────────────────────────────
            [
                'code'          => 'ELEC201',
                'name'          => 'Circuit Theory',
                'name_ar'       => 'نظرية الدوائر الكهربائية',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'ELEC',
                'shared_with'   => [],
            ],
            [
                'code'          => 'ELEC202',
                'name'          => 'Electronics I',
                'name_ar'       => 'الإلكترونيات 1',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'ELEC',
                'shared_with'   => [],
            ],
            [
                'code'          => 'ELEC301',
                'name'          => 'Signals & Systems',
                'name_ar'       => 'الإشارات والأنظمة',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'ELEC',
                'shared_with'   => [],
            ],
            [
                'code'          => 'ELEC401',
                'name'          => 'Power Systems Analysis',
                'name_ar'       => 'تحليل منظومات القدرة',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'ELEC',
                'shared_with'   => [],
            ],
            [
                'code'          => 'ELEC402',
                'name'          => 'Renewable Energy Systems',
                'name_ar'       => 'أنظمة الطاقة المتجددة',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 4,
                'is_elective'   => true,
                'owner'         => 'ELEC',
                'shared_with'   => [],
            ],

            // ── MECHANICAL ENGINEERING (MECH) ─────────────────────────────────────
            [
                'code'          => 'MECH201',
                'name'          => 'Thermodynamics I',
                'name_ar'       => 'الديناميكا الحرارية 1',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'MECH',
                'shared_with'   => [],
            ],
            [
                'code'          => 'MECH301',
                'name'          => 'Machine Design',
                'name_ar'       => 'تصميم الآلات',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'MECH',
                'shared_with'   => [],
            ],
            [
                'code'          => 'MECH302',
                'name'          => 'Manufacturing Processes',
                'name_ar'       => 'عمليات التصنيع',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'MECH',
                'shared_with'   => [],
            ],
            [
                'code'          => 'MECH401',
                'name'          => 'Control Systems',
                'name_ar'       => 'أنظمة التحكم',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'MECH',
                'shared_with'   => ['ELEC'],
            ],

            // ── ARCHITECTURE (ARCH) ───────────────────────────────────────────────
            [
                'code'          => 'ARCH201',
                'name'          => 'Architectural Design I',
                'name_ar'       => 'التصميم المعماري 1',
                'credit_hours'  => 4,
                'lecture_hours' => 2,
                'lab_hours'     => 4,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'ARCH',
                'shared_with'   => [],
            ],
            [
                'code'          => 'ARCH202',
                'name'          => 'History of Architecture',
                'name_ar'       => 'تاريخ العمارة',
                'credit_hours'  => 2,
                'lecture_hours' => 2,
                'lab_hours'     => 0,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'ARCH',
                'shared_with'   => [],
            ],
            [
                'code'          => 'ARCH301',
                'name'          => 'Urban Planning',
                'name_ar'       => 'التخطيط العمراني',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'ARCH',
                'shared_with'   => [],
            ],
            [
                'code'          => 'ARCH401',
                'name'          => 'Sustainable Architecture',
                'name_ar'       => 'العمارة المستدامة',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => true,
                'owner'         => 'ARCH',
                'shared_with'   => [],
            ],

            // ── MEDICINE — shared across all med departments ───────────────────────
            [
                'code'          => 'MED101',
                'name'          => 'Human Anatomy',
                'name_ar'       => 'علم تشريح الإنسان',
                'credit_hours'  => 4,
                'lecture_hours' => 3,
                'lab_hours'     => 2,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'MED-INT',
                'shared_with'   => ['MED-SURG', 'MED-PHAR'],
            ],
            [
                'code'          => 'MED102',
                'name'          => 'Physiology',
                'name_ar'       => 'علم وظائف الأعضاء',
                'credit_hours'  => 4,
                'lecture_hours' => 3,
                'lab_hours'     => 2,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'MED-INT',
                'shared_with'   => ['MED-SURG', 'MED-PHAR'],
            ],
            [
                'code'          => 'MED103',
                'name'          => 'Biochemistry',
                'name_ar'       => 'الكيمياء الحيوية',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'MED-PHAR',
                'shared_with'   => ['MED-INT', 'MED-SURG'],
            ],

            // ── INTERNAL MEDICINE (MED-INT) ───────────────────────────────────────
            [
                'code'          => 'MED-INT301',
                'name'          => 'Clinical Medicine I',
                'name_ar'       => 'الطب السريري 1',
                'credit_hours'  => 4,
                'lecture_hours' => 3,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'MED-INT',
                'shared_with'   => [],
            ],
            [
                'code'          => 'MED-INT401',
                'name'          => 'Cardiology',
                'name_ar'       => 'أمراض القلب',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'MED-INT',
                'shared_with'   => [],
            ],
            [
                'code'          => 'MED-INT402',
                'name'          => 'Endocrinology',
                'name_ar'       => 'الغدد الصماء',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'MED-INT',
                'shared_with'   => [],
            ],

            // ── SURGERY (MED-SURG) ─────────────────────────────────────────────────
            [
                'code'          => 'MED-SURG301',
                'name'          => 'Principles of Surgery',
                'name_ar'       => 'مبادئ الجراحة',
                'credit_hours'  => 4,
                'lecture_hours' => 3,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'MED-SURG',
                'shared_with'   => [],
            ],
            [
                'code'          => 'MED-SURG401',
                'name'          => 'General Surgery',
                'name_ar'       => 'الجراحة العامة',
                'credit_hours'  => 4,
                'lecture_hours' => 3,
                'lab_hours'     => 2,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'MED-SURG',
                'shared_with'   => [],
            ],

            // ── PHARMACOLOGY (MED-PHAR) ───────────────────────────────────────────
            [
                'code'          => 'MED-PHAR301',
                'name'          => 'General Pharmacology',
                'name_ar'       => 'علم الأدوية العام',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'MED-PHAR',
                'shared_with'   => ['MED-INT'],
            ],
            [
                'code'          => 'MED-PHAR401',
                'name'          => 'Clinical Pharmacology',
                'name_ar'       => 'علم الأدوية السريري',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'MED-PHAR',
                'shared_with'   => [],
            ],

            // ── BUSINESS PREPARATORY (BUS-PREP) ───────────────────────────────────
            [
                'code'          => 'BUS001',
                'name'          => 'Principles of Economics',
                'name_ar'       => 'مبادئ الاقتصاد',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'BUS-PREP',
                'shared_with'   => ['MKT', 'BUS-FIN', 'BUS-HR'],
            ],
            [
                'code'          => 'BUS002',
                'name'          => 'Business Mathematics',
                'name_ar'       => 'رياضيات الأعمال',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'BUS-PREP',
                'shared_with'   => ['MKT', 'BUS-FIN', 'BUS-HR'],
            ],
            [
                'code'          => 'BUS003',
                'name'          => 'Introduction to Management',
                'name_ar'       => 'مقدمة في الإدارة',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'BUS-PREP',
                'shared_with'   => ['MKT', 'BUS-FIN', 'BUS-HR'],
            ],

            // ── MARKETING (MKT) ───────────────────────────────────────────────────
            [
                'code'          => 'MKT201',
                'name'          => 'Principles of Marketing',
                'name_ar'       => 'مبادئ التسويق',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'MKT',
                'shared_with'   => ['BUS-HR'],
            ],
            [
                'code'          => 'MKT301',
                'name'          => 'Consumer Behavior',
                'name_ar'       => 'سلوك المستهلك',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'MKT',
                'shared_with'   => [],
            ],
            [
                'code'          => 'MKT302',
                'name'          => 'Digital Marketing',
                'name_ar'       => 'التسويق الرقمي',
                'credit_hours'  => 3,
                'lecture_hours' => 2,
                'lab_hours'     => 2,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'MKT',
                'shared_with'   => [],
            ],
            [
                'code'          => 'MKT401',
                'name'          => 'Strategic Marketing',
                'name_ar'       => 'التسويق الاستراتيجي',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'MKT',
                'shared_with'   => [],
            ],

            // ── FINANCE & BANKING (BUS-FIN) ───────────────────────────────────────
            [
                'code'          => 'BUS-FIN201',
                'name'          => 'Financial Accounting',
                'name_ar'       => 'المحاسبة المالية',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'BUS-FIN',
                'shared_with'   => ['MKT', 'BUS-HR'],
            ],
            [
                'code'          => 'BUS-FIN301',
                'name'          => 'Corporate Finance',
                'name_ar'       => 'تمويل الشركات',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'BUS-FIN',
                'shared_with'   => [],
            ],
            [
                'code'          => 'BUS-FIN302',
                'name'          => 'Investment & Portfolio Management',
                'name_ar'       => 'إدارة الاستثمار والمحافظ',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'BUS-FIN',
                'shared_with'   => [],
            ],
            [
                'code'          => 'BUS-FIN401',
                'name'          => 'Banking Operations & Management',
                'name_ar'       => 'عمليات وإدارة البنوك',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'BUS-FIN',
                'shared_with'   => [],
            ],

            // ── HUMAN RESOURCE MANAGEMENT (BUS-HR) ────────────────────────────────
            [
                'code'          => 'BUS-HR201',
                'name'          => 'Organizational Behavior',
                'name_ar'       => 'السلوك التنظيمي',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'BUS-HR',
                'shared_with'   => ['MKT'],
            ],
            [
                'code'          => 'BUS-HR301',
                'name'          => 'Recruitment & Selection',
                'name_ar'       => 'التوظيف والاختيار',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'BUS-HR',
                'shared_with'   => [],
            ],
            [
                'code'          => 'BUS-HR401',
                'name'          => 'Performance Management',
                'name_ar'       => 'إدارة الأداء',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'BUS-HR',
                'shared_with'   => [],
            ],

            // ── LAW — shared foundations ───────────────────────────────────────────
            [
                'code'          => 'LAW101',
                'name'          => 'Introduction to Law',
                'name_ar'       => 'مقدمة في القانون',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'LAW-PUB',
                'shared_with'   => ['LAW-PRI'],
            ],
            [
                'code'          => 'LAW102',
                'name'          => 'Legal Research & Writing',
                'name_ar'       => 'البحث والكتابة القانونية',
                'credit_hours'  => 2,
                'lecture_hours' => 2,
                'lab_hours'     => 0,
                'level'         => 1,
                'is_elective'   => false,
                'owner'         => 'LAW-PUB',
                'shared_with'   => ['LAW-PRI'],
            ],

            // ── PUBLIC LAW (LAW-PUB) ──────────────────────────────────────────────
            [
                'code'          => 'LAW-PUB201',
                'name'          => 'Constitutional Law',
                'name_ar'       => 'القانون الدستوري',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'LAW-PUB',
                'shared_with'   => [],
            ],
            [
                'code'          => 'LAW-PUB301',
                'name'          => 'Administrative Law',
                'name_ar'       => 'القانون الإداري',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'LAW-PUB',
                'shared_with'   => [],
            ],
            [
                'code'          => 'LAW-PUB401',
                'name'          => 'International Public Law',
                'name_ar'       => 'القانون الدولي العام',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'LAW-PUB',
                'shared_with'   => [],
            ],

            // ── PRIVATE LAW (LAW-PRI) ─────────────────────────────────────────────
            [
                'code'          => 'LAW-PRI201',
                'name'          => 'Civil Law',
                'name_ar'       => 'القانون المدني',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 2,
                'is_elective'   => false,
                'owner'         => 'LAW-PRI',
                'shared_with'   => [],
            ],
            [
                'code'          => 'LAW-PRI301',
                'name'          => 'Commercial Law',
                'name_ar'       => 'القانون التجاري',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 3,
                'is_elective'   => false,
                'owner'         => 'LAW-PRI',
                'shared_with'   => ['LAW-PUB'],
            ],
            [
                'code'          => 'LAW-PRI401',
                'name'          => 'Private International Law',
                'name_ar'       => 'القانون الدولي الخاص',
                'credit_hours'  => 3,
                'lecture_hours' => 3,
                'lab_hours'     => 0,
                'level'         => 4,
                'is_elective'   => false,
                'owner'         => 'LAW-PRI',
                'shared_with'   => [],
            ],
        ];

        // =========================================================================
        // INSERT COURSES + DEPARTMENT_COURSE PIVOT
        // =========================================================================
        foreach ($courses as $data) {
            // Insert course (skip if code already exists)
            $exists = DB::table('courses')->where('code', $data['code'])->exists();
            if (!$exists) {
                $courseId = DB::table('courses')->insertGetId([
                    'code'          => $data['code'],
                    'name'          => $data['name'],
                    'name_ar'       => $data['name_ar'],
                    'credit_hours'  => $data['credit_hours'],
                    'lecture_hours' => $data['lecture_hours'],
                    'lab_hours'     => $data['lab_hours'],
                    'level'         => $data['level'],
                    'is_elective'   => $data['is_elective'],
                    'is_active'     => true,
                    'created_at'    => $now,
                    'updated_at'    => $now,
                ]);
            } else {
                $courseId = DB::table('courses')->where('code', $data['code'])->value('id');
            }

            // Owner department link
            $ownerDeptId = $depts[$data['owner']];
            DB::table('department_course')->updateOrInsert(
                ['department_id' => $ownerDeptId, 'course_id' => $courseId],
                ['is_owner' => true]
            );

            // Shared department links
            foreach ($data['shared_with'] as $sharedCode) {
                $sharedDeptId = $depts[$sharedCode];
                DB::table('department_course')->updateOrInsert(
                    ['department_id' => $sharedDeptId, 'course_id' => $courseId],
                    ['is_owner' => false]
                );
            }
        }
    }
}
